name: internship_task_1
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  get_it: ^7.2.0
  injectable: ^2.1.1
  bloc: ^8.1.2
  provider: ^6.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  injectable_generator: ^2.1.4
  freezed: ^2.3.3
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  generate: true
