name: internship_task_1
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  get_it: ^7.2.0
  injectable: ^2.1.1
  bloc: ^8.1.2
  provider: ^6.0.5
  flutter_screenutil: ^5.8.4
  url_launcher: ^6.1.12
  yandex_mapkit: ^3.3.3
  auto_route: ^7.8.0
  auto_route_generator: ^7.3.0
  firebase_core: ^2.15.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  injectable_generator: ^2.1.4
  freezed: ^2.3.3
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

  fonts:
    - family: YesevaOne
      fonts:
        - asset: assets/fonts/YesevaOne-Regular.ttf
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Regular.ttf
          weight: 400
        - asset: assets/fonts/Jost-Medium.ttf
          weight: 500
        - asset: assets/fonts/Jost-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Jost-Bold.ttf
          weight: 700
